version: "3"

services:
  postgresql:
    image: "postgres:latest"
    restart: "unless-stopped"
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: finque
      POSTGRES_PASSWORD: finque
      POSTGRES_DB: default_database
